import { useEffect, useState } from "react";
import { NavLink, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { useStore } from "./store";
import type { Lifecycle, MissionConfig } from "./types";
import MissionPage from "./pages/MissionPage";

const nav = [
  ["Dashboard", "/", "⌂"], ["Mission", "/mission", "◇"], ["Optimization", "/optimization", "↗"],
  ["Results", "/results", "▤"], ["Mission Setup", "/settings", "⚙"],
];
const fmt = (value: number | undefined, digits = 2) => value === undefined ? "—" : value.toFixed(digits);
function Status({ value }: { value: string }) { return <span className={`status status-${value}`}>{value.replace("_", " ")}</span>; }
function Metric({ label, value, unit }: { label: string; value: string; unit?: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong>{unit && <small>{unit}</small>}</div>; }
function Empty({ title, text, action }: { title: string; text: string; action?: () => void }) { return <div className="empty"><div className="empty-mark">+</div><h3>{title}</h3><p>{text}</p>{action && <button className="button primary" onClick={action}>Open Mission Setup</button>}</div>; }
function Shell() {
  const location = useLocation(); const navigate = useNavigate(); const { mission, lifecycle, socketStatus, error } = useStore();
  return <div className="shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">D</div><div><b>DRONETIC</b><small>Multi-UAV 3D Path Planning</small></div></div>
      <div className="nav-label">MISSION CONTROL</div>
      <nav>{nav.map(([label, path, icon]) => <NavLink key={path} to={path} className={({ isActive }) => isActive ? "nav-item active" : "nav-item"}><i>{icon}</i>{label}</NavLink>)}</nav>
      <div className="sidebar-foot"><span className={`online-dot ${socketStatus === "connected" ? "live" : ""}`} /> <span>{socketStatus === "connected" ? "Live telemetry" : "Awaiting mission"}</span></div>
    </aside>
    <main className="main"><header className="topbar"><div><span className="eyebrow">AUTONOMOUS NAVIGATION / {location.pathname === "/" ? "OVERVIEW" : location.pathname.slice(1).toUpperCase()}</span><h1>{location.pathname === "/" ? "Mission overview" : nav.find((item) => item[1] === location.pathname)?.[0] || "Mission control"}</h1></div><div className="top-actions"><div className="system"><span className="online-dot live" /> SYSTEM ONLINE</div>{mission ? <div className="mission-chip"><span>MISSION</span>{mission.mission_id.slice(0, 8).toUpperCase()}</div> : <button className="button primary compact" onClick={() => navigate("/settings")}>Configure mission</button>}</div></header>{error && <div className="error-banner">{error}<button onClick={() => window.location.reload()}>Dismiss</button></div>}<Routes><Route path="/" element={<Dashboard />} /><Route path="/mission" element={<MissionPage />} /><Route path="/optimization" element={<Optimization />} /><Route path="/results" element={<Results />} /><Route path="/settings" element={<Settings />} /></Routes></main>
  </div>;
}
function Dashboard() {
  const { mission, environment, telemetry, lifecycle } = useStore(); const navigate = useNavigate();
  if (!mission || !environment) return <Empty title="No active mission" text="Generate an environment and configure the optimization engine to begin." action={() => navigate("/settings")} />;
  return <><section className="hero-panel"><div><span className="eyebrow cyan">ACTIVE MISSION / {mission.mission_id.slice(0, 8).toUpperCase()}</span><h2>Fleet telemetry at a glance</h2><p>Real-time state from the Dronetic Python optimization engine.</p></div><Status value={lifecycle} /></section><div className="metrics-grid"><Metric label="Environment" value={`${environment.dimensions.width} × ${environment.dimensions.depth} × ${environment.dimensions.height}`} unit="m" /><Metric label="UAV fleet" value={String(environment.uav_count)} unit="vehicles" /><Metric label="Targets" value={String(environment.target_count)} unit="tasks" /><Metric label="Obstacles" value={String(environment.obstacle_count)} unit="AABB volumes" /></div><section className="content-grid"><Panel title="Optimization telemetry" eyebrow="LIVE ENGINE STATE"><div className="telemetry-grid"><Metric label="Generation" value={`${telemetry.generation ?? "—"} / ${telemetry.total_generations || "—"}`} /><Metric label="Best fitness" value={fmt(telemetry.best_fitness)} /><Metric label="Mean fitness" value={fmt(telemetry.mean_fitness)} /><Metric label="Path distance" value={fmt(telemetry.total_path_distance)} unit="m" /><Metric label="Collisions" value={telemetry.collision_count === undefined ? "—" : String(telemetry.collision_count)} /><Metric label="Task balance" value={fmt(telemetry.balance_penalty)} unit="penalty" /><Metric label="Mutation" value={telemetry.mutation_probability === undefined ? "—" : `${(telemetry.mutation_probability * 100).toFixed(1)}%`} /></div></Panel><Panel title="Fleet status" eyebrow="ROUTE ALLOCATION">{telemetry.target_counts ? <div className="fleet-list">{telemetry.target_counts.map((count, i) => <div className="fleet-row" key={i}><span className="uav-id">UAV {String(i + 1).padStart(2, "0")}</span><span className="bar"><i style={{ width: `${Math.min(100, count / Math.max(...telemetry.target_counts!, 1) * 100)}%` }} /></span><b>{count} targets</b><span>{fmt(telemetry.route_distances?.[i])} m</span></div>)}</div> : <div className="muted">Fleet allocation will appear after the first generation.</div>}</Panel></section></>;
}
function Panel({ title, eyebrow, children }: { title: string; eyebrow?: string; children: React.ReactNode }) { return <section className="panel"><div className="panel-head"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h3>{title}</h3></div></div>{children}</section>; }
function Optimization() {
  const { mission, lifecycle, telemetry, history, control, socketStatus } = useStore();
  if (!mission) return <Empty title="Optimization standing by" text="Create a mission configuration before starting the engine." />;
  const can = (action: string) => action === "start" ? ["idle", "stopped", "completed", "error"].includes(lifecycle) : action === "pause" ? lifecycle === "running" : action === "resume" ? lifecycle === "paused" : ["running", "paused"].includes(lifecycle);
  return <><section className="control-strip"><div><span className="eyebrow cyan">ENGINE STREAM / {socketStatus}</span><h2>Optimization control</h2><p>Generation updates are received directly from the Python engine.</p></div><div className="controls">{(["start", "pause", "resume", "stop"] as const).map((action) => <button key={action} className={`button ${action === "start" ? "primary" : ""}`} disabled={!can(action)} onClick={() => control(action)}>{action.toUpperCase()}</button>)}</div></section><div className="metrics-grid"><Metric label="Lifecycle" value={lifecycle.toUpperCase()} /><Metric label="Generation" value={`${telemetry.generation ?? "—"} / ${telemetry.total_generations || "—"}`} /><Metric label="Best fitness" value={fmt(telemetry.best_fitness)} /><Metric label="Mutation probability" value={telemetry.mutation_probability === undefined ? "—" : `${(telemetry.mutation_probability * 100).toFixed(1)}%`} /></div><section className="content-grid"><Panel title="Fitness history" eyebrow="RECEIVED GENERATIONS"><History data={history.map((p) => p.best_fitness)} color="#43d5e8" label="Best fitness" /></Panel><Panel title="Adaptive mutation" eyebrow="BACKEND VALUES"><History data={history.map((p) => p.mutation_probability === undefined ? undefined : p.mutation_probability * 100)} color="#f0b45b" label="Mutation %" /></Panel><Panel title="Path distance" eyebrow="BACKEND VALUES"><History data={history.map((p) => p.total_path_distance)} color="#72d39b" label="Distance" /></Panel><Panel title="Generation detail" eyebrow="CURRENT BEST"><div className="telemetry-grid"><Metric label="Mean fitness" value={fmt(telemetry.mean_fitness)} /><Metric label="Distance" value={fmt(telemetry.total_path_distance)} unit="m" /><Metric label="Collisions" value={telemetry.collision_count === undefined ? "—" : String(telemetry.collision_count)} /><Metric label="Balance" value={fmt(telemetry.balance_penalty)} /></div></Panel></section></>;
}
function History({ data, color, label }: { data: (number | undefined)[]; color: string; label: string }) { const valid = data.filter((x): x is number => x !== undefined); if (!valid.length) return <div className="chart-empty">No generation events received yet.</div>; const max = Math.max(...valid); const min = Math.min(...valid); const points = valid.map((v, i) => `${i / Math.max(valid.length - 1, 1) * 100},${100 - ((v - min) / Math.max(max - min, 1) * 78 + 10)}`).join(" "); return <div className="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points} fill="none" stroke={color} strokeWidth="1.5" vectorEffect="non-scaling-stroke" /></svg><div className="chart-label"><span>{label}</span><b>{fmt(valid.at(-1))}</b></div></div>; }
function Results() { const { mission, result, lifecycle } = useStore(); if (!mission) return <Empty title="No results available" text="Create and run a mission to populate research-grade results." />; if (!result) return <Empty title={lifecycle === "completed" ? "Finalizing result" : "Awaiting optimization"} text="Final paths, allocation, validation, and diagnostics will appear here when the backend returns them." />; return <><section className="hero-panel"><div><span className="eyebrow cyan">CURRENT RUN / {mission.configuration.algorithm.toUpperCase()}</span><h2>Mission results</h2><p>Final values extracted from the backend engine.</p></div><Status value={result.validation.collision_free ? "completed" : "error"} /></section><div className="metrics-grid"><Metric label="Final fitness" value={fmt(result.metrics.fitness)} /><Metric label="Total path distance" value={fmt(result.metrics.total_distance)} unit="m" /><Metric label="Collisions" value={String(result.metrics.collision_count)} /><Metric label="Task balance" value={fmt(result.metrics.balance_penalty)} /></div><section className="content-grid"><Panel title="UAV allocation" eyebrow="CHROMOSOME → ROUTES">{result.allocation.map((row) => <div className="fleet-row" key={row.uav}><span className="uav-id">UAV {String(row.uav).padStart(2, "0")}</span><b>{row.target_count} targets</b><span>{fmt(row.path_distance)} m</span><small>{row.targets.join(" · ")}</small></div>)}</Panel><Panel title="Validation" eyebrow="COLLISION DIAGNOSTICS"><div className="validation"><strong className={result.validation.collision_free ? "good" : "bad"}>{result.validation.collision_free ? "COLLISION FREE" : "COLLISIONS DETECTED"}</strong><p>{result.validation.total_collisions} segment collisions across {result.validation.routes_with_collision} routes.</p>{result.collisions.map((c, i) => <div className="collision" key={i}>UAV {c.uav} · segment {c.segment_index} · obstacle {c.obstacle}</div>)}</div></Panel></section></>; }
function Settings() {
  const { config, setConfig, createMission } = useStore(); const navigate = useNavigate(); const [busy, setBusy] = useState(false);
  const update = (key: keyof MissionConfig, value: string) => setConfig({ ...config, [key]: key === "algorithm" ? value : Number(value) } as MissionConfig);
  const setDimension = (index: number, value: string) => { const dimensions = [...config.environment_dimensions] as [number, number, number]; dimensions[index] = Number(value); setConfig({ ...config, environment_dimensions: dimensions }); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await createMission(); navigate("/mission"); } finally { setBusy(false); } };
  return <form className="setup" onSubmit={submit}><section className="setup-head"><div><span className="eyebrow cyan">MISSION CONFIGURATION</span><h2>Prepare a navigation run</h2><p>Values are sent directly to the FastAPI engine. Backend validation remains authoritative.</p></div><button className="button primary" disabled={busy}>{busy ? "GENERATING..." : "GENERATE MISSION"}</button></section><div className="form-grid"><Panel title="Environment" eyebrow="SPACE DEFINITION"><div className="fields">{["X", "Y", "Z"].map((label, i) => <label key={label}>{label} dimension (m)<input type="number" value={config.environment_dimensions[i]} onChange={(e) => setDimension(i, e.target.value)} /></label>)}<Field label="Random seed" value={config.seed} onChange={(v) => update("seed", v)} /><Field label="UAV count" value={config.uav_count} onChange={(v) => update("uav_count", v)} /><Field label="Target count" value={config.target_count} onChange={(v) => update("target_count", v)} /><Field label="Obstacle count" value={config.obstacle_count} onChange={(v) => update("obstacle_count", v)} /></div></Panel><Panel title="Genetic algorithm" eyebrow="OPTIMIZATION PARAMETERS"><div className="fields"><Field label="Population size" value={config.population_size} onChange={(v) => update("population_size", v)} /><Field label="Generations" value={config.generations} onChange={(v) => update("generations", v)} /><Field label="Elite count" value={config.elite_count} onChange={(v) => update("elite_count", v)} /><Field label="Crossover probability" value={config.crossover_probability} step="0.01" onChange={(v) => update("crossover_probability", v)} /></div></Panel><Panel title="Mutation & fitness" eyebrow="RESEARCH PARAMETERS"><div className="fields"><Field label="Fixed mutation" value={config.fixed_mutation_probability} step="0.01" onChange={(v) => update("fixed_mutation_probability", v)} /><Field label="Adaptive minimum" value={config.adaptive_mutation_minimum} step="0.01" onChange={(v) => update("adaptive_mutation_minimum", v)} /><Field label="Adaptive maximum" value={config.adaptive_mutation_maximum} step="0.01" onChange={(v) => update("adaptive_mutation_maximum", v)} /><Field label="Collision penalty" value={config.collision_penalty} onChange={(v) => update("collision_penalty", v)} /><Field label="Balance weight" value={config.balance_weight} onChange={(v) => update("balance_weight", v)} /><label>Algorithm<select value={config.algorithm} onChange={(e) => update("algorithm", e.target.value)}><option value="adaptive">Adaptive GA</option><option value="fixed">Fixed / baseline GA</option></select></label></div></Panel></div></form>;
}
function Field({ label, value, onChange, step = "1" }: { label: string; value: number; onChange: (value: string) => void; step?: string }) { return <label>{label}<input type="number" step={step} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
export default function App() { return <Shell />; }
