import { useState } from "react";
import { NavLink, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { useStore } from "./store";
import type { Lifecycle, MissionConfig } from "./types";
import MissionPage from "./pages/MissionPage";
import { Empty, FleetList, fmt, History, Metric, Panel, Status, ValidationBadge } from "./components/controlRoom";

const nav = [
  ["Mission Overview", "/", "⌂", "MISSION"],
  ["Mission", "/mission", "◇", "MISSION"],
  ["Optimization", "/optimization", "↗", "ANALYSIS"],
  ["Results", "/results", "▤", "ANALYSIS"],
  ["Mission Setup", "/settings", "⚙", "CONFIGURATION"],
];

function Shell() {
  const location = useLocation(); const navigate = useNavigate();
  const { mission, lifecycle, socketStatus, backendStatus, error, clearError } = useStore();
  const page = nav.find((item) => item[1] === location.pathname);
  return <div className="shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">D</div><div><b>DRONETIC</b><small>UAV MISSION CONTROL</small></div></div>
      {(["MISSION", "ANALYSIS", "CONFIGURATION"] as const).map((group) => <div className="nav-group" key={group}><div className="nav-label">{group}</div><nav>{nav.filter((item) => item[3] === group).map(([label, path, icon]) => <NavLink key={path} to={path} className={({ isActive }) => isActive ? "nav-item active" : "nav-item"}><i>{icon}</i><span>{label}</span></NavLink>)}</nav></div>)}
      <div className="sidebar-foot"><span className={`online-dot ${socketStatus === "connected" ? "live" : ""}`} /><span>{socketStatus === "connected" ? "LIVE TELEMETRY" : "AWAITING MISSION"}</span></div>
    </aside>
    <main className="main">
      <header className="topbar"><div><span className="eyebrow">DRONETIC / {location.pathname === "/" ? "MISSION OVERVIEW" : page?.[0].toUpperCase()}</span><h1>{location.pathname === "/" ? "Mission Overview" : page?.[0] || "Mission Control"}</h1></div><div className="top-actions"><div className={`system system-${backendStatus}`}><span className={`online-dot ${backendStatus === "online" ? "live" : ""}`} />{backendStatus === "checking" ? "CONNECTING" : backendStatus === "online" ? "SYSTEM NOMINAL" : "CONNECTION LOST"}</div>{mission ? <div className="mission-chip"><span>MISSION</span>{mission.mission_id.slice(0, 8).toUpperCase()}</div> : <button className="button primary compact" onClick={() => navigate("/settings")}>Configure mission</button>}</div></header>
      {error && <div className="error-banner" role="alert"><span><b>MISSION ALERT</b>{error}</span><button onClick={clearError}>Dismiss</button></div>}
      <Routes><Route path="/" element={<Dashboard />} /><Route path="/mission" element={<MissionPage />} /><Route path="/optimization" element={<Optimization />} /><Route path="/results" element={<Results />} /><Route path="/settings" element={<Settings />} /></Routes>
    </main>
  </div>;
}

function Dashboard() {
  const { mission, environment, telemetry, lifecycle } = useStore(); const navigate = useNavigate();
  if (!mission || !environment) return <Empty title="Mission not initialized" text="No active mission is currently loaded. Configure mission parameters to generate the environment and initialize the fleet." action={() => navigate("/settings")} />;
  const fleet = environment.uavs.map((uav, index) => ({ uav: uav.id, targetCount: telemetry.target_counts?.[index] ?? 0, distance: telemetry.route_distances?.[index] }));
  return <div className="page dashboard-page">
    <section className="mission-banner"><div><span className="eyebrow cyan">MISSION {mission.mission_id.slice(0, 8).toUpperCase()}</span><h2>Fleet overview</h2><p>Live mission state from the Python optimization engine.</p></div><div className="banner-status"><span className="online-dot live" />SYSTEM NOMINAL<Status value={lifecycle} /></div></section>
    <div className="metrics-grid"><Metric label="Generation" value={`${telemetry.generation ?? "—"} / ${telemetry.total_generations || "—"}`} /><Metric label="Best fitness" value={fmt(telemetry.best_fitness)} /><Metric label="Path distance" value={fmt(telemetry.total_path_distance)} unit="m" /><Metric label="Collision count" value={telemetry.collision_count === undefined ? "—" : String(telemetry.collision_count)} tone={telemetry.collision_count ? "red" : "green"} /><Metric label="Task balance" value={fmt(telemetry.balance_penalty)} /><Metric label="Mutation probability" value={telemetry.mutation_probability === undefined ? "—" : `${(telemetry.mutation_probability * 100).toFixed(1)}%`} tone="amber" /></div>
    <div className="overview-grid"><Panel title="Fleet status" eyebrow="FLEET TELEMETRY"><FleetList rows={fleet} lifecycle={lifecycle} /></Panel><Panel title="Mission envelope" eyebrow="ENVIRONMENT"><div className="envelope"><div><strong>{environment.dimensions.width} × {environment.dimensions.depth} × {environment.dimensions.height}</strong><span>METERS / X · Y · Z</span></div><div className="envelope-stats"><span><b>{environment.uav_count}</b> UAVS</span><span><b>{environment.target_count}</b> TARGETS</span><span><b>{environment.obstacle_count}</b> OBSTACLES</span></div></div><div className="data-strip"><span>ALGORITHM</span><b>{mission.configuration.algorithm === "adaptive" ? "ADAPTIVE GENETIC ALGORITHM" : "FIXED / BASELINE GA"}</b></div></Panel></div>
    <div className="content-grid"><Panel title="Optimization telemetry" eyebrow="LIVE ENGINE STATE"><div className="telemetry-grid"><Metric label="Mean fitness" value={fmt(telemetry.mean_fitness)} /><Metric label="Generation" value={`${telemetry.generation ?? "—"} / ${telemetry.total_generations || "—"}`} /><Metric label="Mutation" value={telemetry.mutation_probability === undefined ? "—" : `${(telemetry.mutation_probability * 100).toFixed(1)}%`} tone="amber" /></div></Panel><Panel title="Target allocation" eyebrow="TASK DISTRIBUTION">{telemetry.target_counts ? <FleetList rows={fleet} lifecycle={lifecycle} /> : <div className="muted">WAITING FOR GENERATION DATA</div>}</Panel></div>
  </div>;
}

function Optimization() {
  const { mission, lifecycle, telemetry, history, control, socketStatus } = useStore();
  if (!mission) return <Empty title="Optimization standing by" text="Create a mission configuration before starting the engine." />;
  const can = (action: string) => action === "start" ? ["idle", "stopped", "completed", "error"].includes(lifecycle) : action === "pause" ? lifecycle === "running" : action === "resume" ? lifecycle === "paused" : ["running", "paused"].includes(lifecycle);
  return <div className="page optimization-page"><section className="control-strip"><div><span className="eyebrow cyan">ENGINE STREAM / {socketStatus.toUpperCase()}</span><h2>Optimization control center</h2><p>Generation updates are received directly from the Python engine.</p></div><div className="controls">{(["start", "pause", "resume", "stop"] as const).map((action) => <button key={action} className={`button ${action === "start" ? "primary" : ""}`} disabled={!can(action)} onClick={() => control(action)}>{action.toUpperCase()}</button>)}</div></section><div className="status-ribbon"><span>OPTIMIZATION STATE</span><Status value={lifecycle} /><span className="ribbon-divider" /><span>GENERATION <b>{telemetry.generation ?? "—"} / {telemetry.total_generations || "—"}</b></span></div><div className="metrics-grid"><Metric label="Best fitness" value={fmt(telemetry.best_fitness)} /><Metric label="Mean fitness" value={fmt(telemetry.mean_fitness)} /><Metric label="Path distance" value={fmt(telemetry.total_path_distance)} unit="m" /><Metric label="Collisions" value={telemetry.collision_count === undefined ? "—" : String(telemetry.collision_count)} tone={telemetry.collision_count ? "red" : "green"} /><Metric label="Task balance" value={fmt(telemetry.balance_penalty)} /><Metric label="Mutation probability" value={telemetry.mutation_probability === undefined ? "—" : `${(telemetry.mutation_probability * 100).toFixed(1)}%`} tone="amber" /></div><section className="content-grid chart-grid"><Panel title="Best fitness" eyebrow="CONVERGENCE / BACKEND EVENTS"><History data={history.map((p) => p.best_fitness)} color="#43d5e8" label="BEST FITNESS" /></Panel><Panel title="Mean fitness" eyebrow="POPULATION TELEMETRY"><History data={history.map((p) => p.mean_fitness)} color="#8aa9ff" label="MEAN FITNESS" /></Panel><Panel title="Adaptive mutation" eyebrow="EXPLORATION → EXPLOITATION"><History data={history.map((p) => p.mutation_probability === undefined ? undefined : p.mutation_probability * 100)} color="#f0b45b" label="MUTATION %" /></Panel><Panel title="Path distance" eyebrow="ROUTE TELEMETRY"><History data={history.map((p) => p.total_path_distance)} color="#72d39b" label="DISTANCE" /></Panel></section></div>;
}

function Results() {
  const { mission, environment, result, lifecycle } = useStore();
  if (!mission) return <Empty title="Mission debrief unavailable" text="Create and run a mission to populate research-grade results." />;
  if (!result) return <Empty title={lifecycle === "completed" ? "Finalizing debrief" : "Awaiting optimization"} text="Final paths, allocation, validation, and diagnostics will appear here when the backend returns them." />;
  const allocatedTargets = new Set(result.allocation.flatMap((row) => row.targets)).size;
  return <div className="page results-page"><section className="mission-banner debrief-banner"><div><span className="eyebrow cyan">MISSION DEBRIEF / {mission.configuration.algorithm.toUpperCase()}</span><h2>Engineering analysis</h2><p>Final values extracted from the backend engine. No reference-paper comparison is implied.</p></div><ValidationBadge result={result} /></section><div className="metrics-grid"><Metric label="Final fitness" value={fmt(result.metrics.fitness)} /><Metric label="Total path distance" value={fmt(result.metrics.total_distance)} unit="m" /><Metric label="Collision count" value={String(result.metrics.collision_count)} tone={result.metrics.collision_count ? "red" : "green"} /><Metric label="Task-balance standard deviation" value={fmt(result.metrics.balance_penalty)} /><Metric label="Target completion" value={`${allocatedTargets} / ${environment?.target_count ?? "—"}`} tone="green" /></div><div className="content-grid"><Panel title="Fleet performance" eyebrow="UAV / ROUTE ANALYSIS"><div className="fleet-table-head"><span>VEHICLE</span><span>TARGETS</span><span>DISTANCE</span><span>ROUTE</span></div>{result.allocation.map((row) => <div className="fleet-table-row" key={row.uav}><span className="uav-id">UAV-{String(row.uav).padStart(2, "0")}</span><b>{row.target_count}</b><span>{fmt(row.path_distance)} m</span><small>{row.targets.join(" · ")}</small></div>)}</Panel><Panel title="Validation" eyebrow="MISSION INTEGRITY"><div className="validation"><ValidationBadge result={result} /><p>{result.validation.total_collisions} segment collisions across {result.validation.routes_with_collision} routes.</p>{result.collisions.map((c, i) => <div className="collision" key={i}>UAV {c.uav} · segment {c.segment_index} · obstacle {c.obstacle}</div>)}</div></Panel></div></div>;
}

function Settings() {
  const { config, setConfig, createMission } = useStore(); const navigate = useNavigate(); const [busy, setBusy] = useState(false);
  const update = (key: keyof MissionConfig, value: string) => setConfig({ ...config, [key]: key === "algorithm" ? value : Number(value) } as MissionConfig);
  const setDimension = (index: number, value: string) => { const dimensions = [...config.environment_dimensions] as [number, number, number]; dimensions[index] = Number(value); setConfig({ ...config, environment_dimensions: dimensions }); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await createMission(); navigate("/mission"); } finally { setBusy(false); } };
  return <form className="setup page" onSubmit={submit}><section className="setup-head"><div><span className="eyebrow cyan">MISSION PLANNING CONSOLE</span><h2>Configure mission parameters</h2><p>Values are sent directly to the FastAPI engine. Backend validation remains authoritative.</p></div><button className="button primary generate-button" disabled={busy}>{busy ? "INITIALIZING..." : "GENERATE MISSION"}</button></section><div className="form-grid"><Panel title="Environment" eyebrow="SPACE DEFINITION"><div className="fields">{["X", "Y", "Z"].map((label, i) => <label key={label}>{label} dimension (m)<input type="number" value={config.environment_dimensions[i]} onChange={(e) => setDimension(i, e.target.value)} /></label>)}<Field label="Random seed" value={config.seed} onChange={(v) => update("seed", v)} /><Field label="UAV count" value={config.uav_count} onChange={(v) => update("uav_count", v)} /><Field label="Target count" value={config.target_count} onChange={(v) => update("target_count", v)} /><Field label="Obstacle count" value={config.obstacle_count} onChange={(v) => update("obstacle_count", v)} /></div></Panel><Panel title="Genetic algorithm" eyebrow="OPTIMIZATION PARAMETERS"><div className="fields"><Field label="Population size" value={config.population_size} onChange={(v) => update("population_size", v)} /><Field label="Generations" value={config.generations} onChange={(v) => update("generations", v)} /><Field label="Elite count" value={config.elite_count} onChange={(v) => update("elite_count", v)} /><Field label="Crossover probability" value={config.crossover_probability} step="0.01" onChange={(v) => update("crossover_probability", v)} /></div></Panel><Panel title="Mutation & fitness" eyebrow="RESEARCH OBJECTIVE"><div className="fields"><Field label="Fixed mutation" value={config.fixed_mutation_probability} step="0.01" onChange={(v) => update("fixed_mutation_probability", v)} /><Field label="Adaptive minimum" value={config.adaptive_mutation_minimum} step="0.01" onChange={(v) => update("adaptive_mutation_minimum", v)} /><Field label="Adaptive maximum" value={config.adaptive_mutation_maximum} step="0.01" onChange={(v) => update("adaptive_mutation_maximum", v)} /><Field label="Collision penalty" value={config.collision_penalty} onChange={(v) => update("collision_penalty", v)} /><Field label="Balance weight" value={config.balance_weight} onChange={(v) => update("balance_weight", v)} /><label>Algorithm<select value={config.algorithm} onChange={(e) => update("algorithm", e.target.value)}><option value="adaptive">Adaptive GA</option><option value="fixed">Fixed / baseline GA</option></select></label></div></Panel></div></form>;
}
function Field({ label, value, onChange, step = "1" }: { label: string; value: number; onChange: (value: string) => void; step?: string }) { return <label>{label}<input type="number" step={step} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
export default function App() { return <Shell />; }
